name: mageckenv
channels:
  - https://repo.anaconda.com/pkgs/free/
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5
  - adjusttext=1.3.0
  - anndata=0.12.6
  - appnope=0.1.4
  - arpack=3.9.1
  - array-api-compat=1.12.0
  - asttokens=3.0.1
  - attrs=25.4.0
  - backports.zstd=1.1.0
  - blas=2.304
  - blas-devel=3.11.0
  - blinker=1.9.0
  - blosc=1.21.6
  - bottleneck=1.6.0
  - brotli=1.2.0
  - brotli-bin=1.2.0
  - brotli-python=1.2.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.12.2
  - cached-property=2.0.1
  - certifi=2025.11.12
  - charset-normalizer=3.4.4
  - click=8.3.1
  - colorama=0.4.6
  - comm=0.2.3
  - contourpy=1.3.3
  - cpp-expected=1.3.1
  - cycler=0.12.1
  - dcor=0.6
  - debugpy=1.8.17
  - decorator=5.2.1
  - decoupler-py=2.1.2
  - docrep=0.3.2
  - donfig=0.8.1.post1
  - executing=2.2.1
  - expat=2.7.3
  - flask=3.1.2
  - fmt=12.0.0
  - fonttools=4.61.0
  - freetype=2.14.1
  - glpk=5.0
  - gmp=6.3.0
  - google-crc32c=1.7.1
  - h2=4.3.0
  - h5py=3.15.1
  - hdf5=1.14.6
  - hpack=4.1.0
  - hyperframe=6.1.0
  - idna=3.11
  - igraph=0.10.16
  - importlib-metadata=8.7.0
  - importlib-resources=6.5.2
  - importlib_resources=6.5.2
  - inflect=7.5.0
  - ipykernel=7.1.0
  - ipython=9.8.0
  - ipython_pygments_lexers=1.1.1
  - ipywidgets=8.1.8
  - itsdangerous=2.2.0
  - jansson=2.14.1
  - jedi=0.19.2
  - jinja2=3.1.6
  - joblib=1.5.2
  - jupyter_client=8.6.3
  - jupyter_core=5.9.1
  - jupyterlab_widgets=3.0.16
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lcms2=2.17
  - legacy-api-wrap=1.5
  - legendkit=0.3.4
  - lerc=4.0.0
  - libaec=1.1.4
  - libarchive=3.8.2
  - libblas=3.11.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcblas=3.11.0
  - libcrc32c=1.1.2
  - libcurl=8.17.0
  - libcxx=21.1.7
  - libdeflate=1.25
  - libedit=3.1.20250104
  - libev=4.33
  - libexpat=2.7.3
  - libffi=3.5.2
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libhwloc=2.12.1
  - libiconv=1.18
  - libjpeg-turbo=3.1.2
  - libkrb5=1.21.3
  - liblapack=3.11.0
  - liblapacke=3.11.0
  - libllvm14=14.0.6
  - libllvm20=20.1.8
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libmamba=2.4.0
  - libnghttp2=1.67.1
  - libopenblas=0.3.30
  - libopenjpeg=2.5.4
  - libpng=1.6.53
  - libsodium=1.0.20
  - libsolv=0.7.35
  - libsqlite=3.51.1
  - libssh2=1.11.1
  - libtiff=4.7.1
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxgboost=3.1.2
  - libxml2=2.13.9
  - libzlib=1.3.1
  - llvm-openmp=21.1.7
  - llvmlite=0.45.1
  - lmdb=0.9.31
  - lz4-c=1.9.4
  - mageck=0.5.9.5
  - mamba=2.4.0
  - markupsafe=3.0.3
  - marsilea=0.5.6
  - matplotlib=3.10.8
  - matplotlib-base=3.10.8
  - matplotlib-inline=0.2.1
  - more-itertools=10.8.0
  - msgpack-python=1.1.2
  - munkres=1.1.4
  - natsort=8.4.0
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.6
  - nlohmann_json-abi=3.12.0
  - numba=0.62.1
  - numexpr=2.14.1
  - numpy=2.3.5
  - numpy-base=2.3.5
  - omnipath=1.0.8
  - openblas=0.3.30
  - openjpeg=2.5.4
  - openssl=3.6.0
  - packaging=25.0
  - pandas=2.3.3
  - parso=0.8.5
  - patsy=1.0.2
  - pexpect=4.9.0
  - pillow=12.0.0
  - pip=25.3
  - platformdirs=4.5.1
  - prompt-toolkit=3.0.52
  - psutil=7.1.3
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - py-xgboost=3.1.2
  - pybind11-abi=11
  - pygments=2.19.2
  - pynndescent=0.5.13
  - pyparsing=3.2.5
  - pysocks=1.7.1
  - python=3.11.14
  - python-dateutil=2.9.0post0
  - python-igraph=0.11.9
  - python-tzdata=2025.2
  - python_abi=3.11
  - pytz=2025.2
  - pyyaml=6.0.3
  - pyzmq=27.1.0
  - qhull=2020.2
  - readline=8.3
  - reproc=14.2.5.post0
  - reproc-cpp=14.2.5.post0
  - requests=2.32.5
  - scanpy=1.11.5
  - scikit-learn=1.7.2
  - scipy=1.16.3
  - seaborn=0.13.2
  - session-info2=0.2.3
  - setuptools=80.9.0
  - simdjson=4.2.2
  - six=1.17.0
  - sqlite=3.51.1
  - stack_data=0.6.3
  - statsmodels=0.14.6
  - tbb=2022.3.0
  - texttable=1.7.0
  - threadpoolctl=3.6.0
  - tk=8.6.15
  - tornado=6.5.2
  - tqdm=4.67.1
  - traitlets=5.14.3
  - typeguard=4.4.4
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - tzdata=2025b
  - umap-learn=0.5.9.post2
  - unicodedata2=17.0.0
  - urllib3=2.6.0
  - wcwidth=0.2.14
  - werkzeug=3.1.4
  - wheel=0.45.1
  - widgetsnbextension=4.0.15
  - wrapt=2.0.1
  - xgboost=3.1.2
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - yaml=0.2.5
  - yaml-cpp=0.8.0
  - zarr=3.1.5
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.3.1
  - zlib-ng=2.3.2
  - zstd=1.5.7
  - pip:
      - formulaic==1.2.1
      - formulaic-contrasts==1.0.0
      - interface-meta==1.3.0
      - narwhals==2.13.0
      - numcodecs==0.16.5
      - plotly==6.5.2
      - pyarrow==22.0.0
      - pydeseq2==0.5.3
prefix: /Users/mubasher.mohammed/miniconda3/envs/mageckenv

